version: '3.8'
services:
  postgres:
    container_name: db-postgres
    image: postgres:11.16-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pizza
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data